# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to my blog # ex. I m Chuan
name: Lu Chen # ex. DONGChuan
email: none954@163.com
location: Beijing, China # ex. Nice, France
#company: MyCompany
#company_url: my_company_website
github_url: https://github.com/strongman1995 # ex. https://github.com/DONGChuan
github_username: strongman1995 # ex. DONGChuan
description: Don't worry, be happy
favicon: favicon.png # Image must be in assets/images
repository: strongman1995/strongman1995.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://strongman1995.github.io
url: http://strongman1995.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
#disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /about
    label: About

  -
    href: /blog
    label: Blog

  -
    href: /open-source
    label: Open-Source

  -
    href: /bookmark
    label: Bookmark


# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-139849944-1'  # ex. UA-72165600-X

# For about.html. Fell free to create your own!
skill_software_keywords: [Python, Shell, C++, Java, JavaScript, SQL, SQLite]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
